name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main # Or your default branch
  pull_request: # Optional: build on pull requests for testing
  workflow_dispatch: # Allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: # Ensure only one concurrent deployment for this workflow and ref
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes (if relying on git submodules)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2 # Or newer, like v3
        with:
          hugo-version: "latest" # Or a specific version like '0.125.0'
          extended: true

      - name: Setup Node.js # For Tailwind CSS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci # Requires package-lock.json

      # Hugo builds the site, including processing CSS with PostCSS (Tailwind) via Hugo Pipes
      - name: Build Hugo site
        run: hugo --minify # Output is in 'public' folder by default

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only deploy on push to main
        uses: peaceiris/actions-gh-pages@v3 # Or newer, like v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Directory Hugo builds to
          publish_branch: gh-pages # Deploy to this branch
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          # cname: your-custom-domain.com # Uncomment if you have a custom domain
